# Site settings
title: Cozy Journal
author:
  name: SY
  email: developerSY@gmail.com
description: "Cozy Journal is a AI powered diary."

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
